import {
  Activity,
  AlertCircle,
  AlertTriangle,
  Archive,
  BaggageClaim,
  BarChart2,
  Wallet,
  Bell,
  Library,
  Building,
  Building2,
  BuildingIcon,
  Calendar,
  CarFront,
  CheckCircle,
  CheckSquare,
  Clipboard,
  ClipboardCheck,
  Computer,
  CreditCard,
  DollarSign,
  FileLock,
  FileText,
  Headphones,
  Home,
  Layers,
  Lightbulb,
  LineChart,
  Lock,
  LogIn,
  Map,
  MessageCircle,
  Mountain,
  Package,
  PackageSearch,
  PhoneIcon,
  Pin,
  Printer,
  Server,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Store,
  Tag,
  Ticket,
  TrendingUp,
  Truck,
  User,
  User2,
  Users,
  Warehouse,
  Repeat,
  TrendingDown,
  Tags,
} from "lucide-react";

export const navConfig = [
  {
    label: "Quick Links",
    path: "/quick-links",
    icon: Lightbulb,
    alwaysOpen: true,
    permissionKeys: [
      "Shipment access",
      "Outsourced Shipment access",
      "Pickup Unassigned Shipment access",
      "Archived Shipment access",
      "COD collections access",
      "Drivers access",
    ],
    permissions: [
      { id: "Shipment access", name: "View" },
      { id: "Outsourced Shipment access", name: "View" },
      { id: "Pickup Unassigned Shipment access", name: "View" },
      { id: "Archived Shipment access", name: "View" },
      { id: "COD collections access", name: "View" },
      { id: "Drivers access", name: "View" },
    ],
    items: [
      {
        label: "Shipments",
        isQuickLink: true,
        path: "/shipments",
        plusLink: "/shipments/create",
        icon: Clipboard,
        permissionKey: "Shipment access",
        permissions: [
          { id: "Shipment access", name: "View" },
          { id: "Shipment create", name: "Create" },
          { id: "Shipment update", name: "Edit" },
          { id: "Shipment delete", name: "Delete" },
          { id: "Shipment Print access", name: "Print" },
          { id: "Shipment Import access", name: "Import" },
          { id: "Shipment Import Template access", name: "Import Template" },
          { id: "Shipment Export access", name: "Export" },
        ],
      },
      {
        label: "Outsourced Shipments",
        isQuickLink: false,
        path: "outsourced-shipment",
        plusLink: "/outsourced-shipment/create",
        icon: Truck,
        permissionKey: "Outsourced Shipment access",
        permissions: [
          { id: "Outsourced Shipment access", name: "View" },
          { id: "Outsourced Shipment create", name: "Create" },
          { id: "Outsourced Shipment update", name: "Edit" },
          { id: "Outsourced Shipment delete", name: "Delete" },
          { id: "Outsourced Shipment print", name: "Print" },
          { id: "Outsourced Shipment import", name: "Import" },
          { id: "Outsourced Shipment import template", name: "Import Template" },
          { id: "Outsourced Shipment export", name: "Export" },
        ],
      },
      {
        label: "shipment pickup unassigned",
        isQuickLink: false,
        path: "/shipments/pickup-unassigned",
        icon: PackageSearch,
        permissionKey: "Pickup Unassigned Shipment access",
        permissions: [
          { id: "Pickup Unassigned Shipment access", name: "View" },
          { id: "Pickup Unassigned Shipment create", name: "Create" },
          { id: "Pickup Unassigned Shipment update", name: "Edit" },
          { id: "Pickup Unassigned Shipment delete", name: "Delete" },
        ],
      },
      {
        label: "shipment unregistered",
        isQuickLink: false,
        path: "/shipments/unregistered",
        icon: PackageSearch,
        permissionKey: "Pickup Unassigned Shipment access",
        permissions: [
          { id: "Pickup Unassigned Shipment access", name: "View" },
          { id: "Pickup Unassigned Shipment create", name: "Create" },
          { id: "Pickup Unassigned Shipment update", name: "Edit" },
          { id: "Pickup Unassigned Shipment delete", name: "Delete" },
        ],
      },
      {
        label: "Archived Shipments",
        isQuickLink: true,
        path: "/archived-shipments",
        plusLink: "/shipments/create",
        icon: Archive,
        permissionKey: "Archived Shipment access",
        permissions: [
          { id: "Archived Shipment access", name: "View" },
          { id: "Archived Shipment update", name: "Restore" },
          { id: "Archived Shipment delete", name: "Delete" },
        ],
      },
      {
        label: "COD Collection",
        path: "/cod",
        icon: CreditCard,
        permissionKey: "COD collections access",
        permissions: [
          { id: "COD collections access", name: "View" },
          { id: "COD collections create", name: "Create" },
          { id: "COD collections update", name: "Edit" },
          { id: "COD collections delete", name: "Delete" },
        ],
        isQuickLink: true,
      },
      {
        label: "Drivers",
        path: "/drivers",
        plusLink: "/users/create-driver",
        icon: Users,
        permissionKey: "Drivers access",
        permissions: [
          { id: "Drivers access", name: "View" },
          { id: "Drivers create", name: "Create" },
          { id: "Drivers update", name: "Edit" },
          { id: "Drivers delete", name: "Delete" },
        ],
        isQuickLink: true,
      },
    ],
  },
  {
    label: "Dashboard",
    path: "/dashboard",
    icon: Computer,
    permissionKeys: [
      "Dashboard access",
      "Quick Stats access",
      "Alerts access",
      "Daily Summary access",
      "Notification access",
    ],
    permissions: [
      { id: "Dashboard access", name: "View" },
      { id: "Quick Stats access", name: "View" },
      { id: "Alerts access", name: "View" },
      { id: "Daily Summary access", name: "View" },
      { id: "Notification access", name: "View" },
    ],
    items: [
      {
        label: "Overview",
        path: "/dashboard",
        icon: BarChart2,
        permissionKey: "Dashboard access",
        permissions: [
          { id: "Dashboard access", name: "View" },
          { id: "Dashboard create", name: "Create" },
          { id: "Dashboard update", name: "Edit" },
          { id: "Dashboard delete", name: "Delete" },
        ],
      },
      {
        label: "Quick Stats",
        path: "/quick-stats",
        icon: TrendingUp,
        permissionKey: "Quick Stats access",
        permissions: [
          { id: "Quick Stats access", name: "View" },
          { id: "Quick Stats create", name: "Create" },
          { id: "Quick Stats update", name: "Edit" },
          { id: "Quick Stats delete", name: "Delete" },
        ],
      },
      {
        label: "Alerts",
        path: "/alerts",
        icon: Bell,
        permissionKey: "Alerts access",
        permissions: [
          { id: "Alerts access", name: "View" },
          { id: "Alerts create", name: "Create" },
          { id: "Alerts update", name: "Edit" },
          { id: "Alerts delete", name: "Delete" },
        ],
      },
      {
        label: "Daily Summary",
        path: "/daily-summary",
        icon: Calendar,
        permissionKey: "Daily Summary access",
        permissions: [
          { id: "Daily Summary access", name: "View" },
          { id: "Daily Summary create", name: "Create" },
          { id: "Daily Summary update", name: "Edit" },
          { id: "Daily Summary delete", name: "Delete" },
        ],
      },
      {
        label: "Notifications",
        path: "/notifications",
        icon: Bell,
        permissionKey: "Notification access",
        permissions: [{ id: "Notification access", name: "View" }],
      },
    ],
  },
  {
    label: "Main",
    icon: User,
    permissionKeys: [
      "Unit access",
      "Governorate access",
      "State access",
      "Place access",
      "City access",
      "Hub access",
      "Station access",
      "Branch access",
      "Zone access",
      "Role access",
      "Permission access",
      "User access",
      "Setting access",
    ],
    permissions: [
      { id: "Unit access", name: "View" },
      { id: "Governorate access", name: "View" },
      { id: "State access", name: "View" },
      { id: "Place access", name: "View" },
      { id: "City access", name: "View" },
      { id: "Hub access", name: "View" },
      { id: "Station access", name: "View" },
      { id: "Branch access", name: "View" },
      { id: "Zone access", name: "View" },
      { id: "Role access", name: "View" },
      { id: "Permission access", name: "View" },
      { id: "User access", name: "View" },
      { id: "Setting access", name: "View" },
    ],
    items: [
      {
        label: "Units",
        path: "/units",
        icon: Building,
        permissionKey: "Unit access",
        permissions: [
          { id: "Unit access", name: "View" },
          { id: "Unit create", name: "Create" },
          { id: "Unit update", name: "Edit" },
          { id: "Unit delete", name: "Delete" },
          { id: "Unit export", name: "Export" },
        ],
      },
      {
        label: "Governorates",
        path: "/governorates",
        icon: Map,
        permissionKey: "Governorate access",
        permissions: [
          { id: "Governorate access", name: "View" },
          { id: "Governorate create", name: "Create" },
          { id: "Governorate update", name: "Edit" },
          { id: "Governorate delete", name: "Delete" },
          { id: "Governorate export", name: "Export" },
        ],
      },
      {
        label: "States",
        path: "/states",
        icon: Mountain,
        permissionKey: "State access",
        permissions: [
          { id: "State access", name: "View" },
          { id: "State create", name: "Create" },
          { id: "State update", name: "Edit" },
          { id: "State delete", name: "Delete" },
          { id: "State import", name: "Import" },
          { id: "State export", name: "Export" },
        ],
      },
      {
        label: "Places",
        path: "/places",
        icon: Building2,
        permissionKey: "Place access",
        permissions: [
          { id: "Place access", name: "View" },
          { id: "Place create", name: "Create" },
          { id: "Place update", name: "Edit" },
          { id: "Place delete", name: "Delete" },
          { id: "Place import", name: "Import" },
        ],
      },
      {
        label: "Cities",
        path: "/cities",
        icon: BuildingIcon,
        permissionKey: "City access",
        permissions: [
          { id: "City access", name: "View" },
          { id: "City create", name: "Create" },
          { id: "City update", name: "Edit" },
          { id: "City delete", name: "Delete" },
        ],
      },
      {
        label: "Hubs",
        path: "/hubs",
        icon: CarFront,
        permissionKey: "Hub access",
        permissions: [
          { id: "Hub access", name: "View" },
          { id: "Hub create", name: "Create" },
          { id: "Hub update", name: "Edit" },
          { id: "Hub delete", name: "Delete" },
          { id: "Hub export", name: "Export" },
        ],
      },
      {
        label: "Stations",
        path: "/stations",
        icon: Warehouse,
        permissionKey: "Station access",
        permissions: [
          { id: "Station access", name: "View" },
          { id: "Station create", name: "Create" },
          { id: "Station update", name: "Edit" },
          { id: "Station delete", name: "Delete" },
          { id: "Station export", name: "Export" },
        ],
      },
      {
        label: "Branches",
        path: "/branches",
        icon: Home,
        permissionKey: "Branch access",
        permissions: [
          { id: "Branch access", name: "View" },
          { id: "Branch create", name: "Create" },
          { id: "Branch update", name: "Edit" },
          { id: "Branch delete", name: "Delete" },
        ],
      },
      {
        label: "Zones Map",
        path: "/zones-map",
        icon: Map,
        permissionKey: "Zone access",
        permissions: [
          { id: "Zone access", name: "View" },
          { id: "Zone create", name: "Create" },
          { id: "Zone update", name: "Edit" },
          { id: "Zone delete", name: "Delete" },
          { id: "Zone import", name: "Import" },
          { id: "Zone export", name: "Export" },
        ],
      },
      {
        label: "Routing rules",
        path: "/routing-rules",
        plusLink: "/routing-rules/create-zone",
        icon: Pin,
        permissionKey: "Rule access",
        permissions: [
          { id: "Rule access", name: "View" },
          { id: "Rule create", name: "Create" },
          { id: "Rule update", name: "Edit" },
          { id: "Rule delete", name: "Delete" },
        ],
      },
      {
        label: "Roles",
        path: "/roles",
        plusLink: "/roles/create-role",
        icon: Users,
        permissionKey: "Role access",
        permissions: [
          { id: "Role access", name: "View" },
          { id: "Role create", name: "Create" },
          { id: "Role update", name: "Edit" },
          { id: "Role delete", name: "Delete" },
          { id: "Role import", name: "Import" },
          { id: "Role export", name: "Export" },
        ],
      },
      {
        label: "Permissions",
        path: "/permissions",
        icon: Lock,
        permissionKey: "Permission access",
        permissions: [
          { id: "Permission access", name: "View" },
          { id: "Permission create", name: "Create" },
          { id: "Permission update", name: "Edit" },
          { id: "Permission delete", name: "Delete" },
          { id: "Permission export", name: "Export" },
        ],
      },
      {
        label: "Users",
        path: "/users",
        plusLink: "/users/create-user",
        icon: Users,
        permissionKey: "User access",
        permissions: [
          { id: "User access", name: "View" },
          { id: "User create", name: "Create" },
          { id: "User update", name: "Edit" },
          { id: "User delete", name: "Delete" },
          { id: "User import", name: "Import" },
          { id: "User export", name: "Export" },
        ],
      },
      {
        label: "Dashboard Configurations",
        path: "/status-transition-config",
        icon: Settings,
        permissionKey: "Setting access",
        permissions: [
          { id: "Setting access", name: "View" },
          { id: "Setting create", name: "Create" },
          { id: "Setting update", name: "Edit" },
          { id: "Setting delete", name: "Delete" },
        ],
      },
    ],
  },
  {
    label: "Shipment Management",
    icon: Package,
    permissionKeys: [
      "Shipment access",
      "Shipment Future access",
      "Outsourced Shipment access",
      "Archived Shipment access",
      "Shipment Status access",
      "Operation access",
      "Delivery Exception access",
      "Problems access",
    ],
    permissions: [
      { id: "Shipment access", name: "View" },
      { id: "Shipment Future access", name: "View" },
      { id: "Outsourced Shipment access", name: "View" },
      { id: "Archived Shipment access", name: "View" },
      { id: "Shipment Status access", name: "View" },
      { id: "Operation access", name: "View" },
      { id: "Delivery Exception access", name: "View" },
      { id: "Problems access", name: "View" },
    ],
    items: [
      {
        label: "Shipments",
        isQuickLink: false,
        path: "/shipments",
        plusLink: "/shipments/create",
        icon: Clipboard,
        permissionKey: "Shipment access",
        permissions: [
          { id: "Shipment access", name: "View" },
          { id: "Shipment create", name: "Create" },
          { id: "Shipment update", name: "Edit" },
          { id: "Shipment delete", name: "Delete" },
          { id: "Shipment Print access", name: "Print" },
          { id: "Shipment Import access", name: "Import" },
          { id: "Shipment Import Template access", name: "Import Template" },
          { id: "Shipment Export access", name: "Export" },
        ],
      },
      {
        label: "Future Shipments",
        isQuickLink: false,
        path: "/future-shipments",
        plusLink: "/shipments/create",
        icon: Clipboard,
        permissionKey: "Shipment Future access",
        permissions: [
          { id: "Shipment Future access", name: "View" },
          { id: "Shipment Future delete", name: "Delete" },
          { id: "Shipment Future print", name: "Print" },
        ],
      },
      {
        label: "Outsourced Shipments",
        isQuickLink: false,
        path: "outsourced-shipment",
        plusLink: "/outsourced-shipment/create",
        icon: Truck,
        permissionKey: "Outsourced Shipment access",
        permissions: [
          { id: "Outsourced Shipment access", name: "View" },
          { id: "Outsourced Shipment create", name: "Create" },
          { id: "Outsourced Shipment update", name: "Edit" },
          { id: "Outsourced Shipment delete", name: "Delete" },
          { id: "Outsourced Shipment print", name: "Print" },
          { id: "Outsourced Shipment import", name: "Import" },
          { id: "Outsourced Shipment import template", name: "Import Template" },
          { id: "Outsourced Shipment export", name: "Export" },
        ],
      },
      {
        label: "Archived Shipments",
        isQuickLink: true,
        path: "/archived-shipments",
        plusLink: "/shipments/create",
        icon: Archive,
        permissionKey: "Archived Shipment access",
        permissions: [
          { id: "Archived Shipment access", name: "View" },
          { id: "Archived Shipment update", name: "Restore" },
          { id: "Archived Shipment delete", name: "Delete" },
        ],
      },
      {
        label: "Customer Created Shipments",
        path: "/customer-created-shipments",
        icon: User,
        permissionKey: "Customer Created Shipments access",
        permissions: [
          { id: "Customer Created Shipments access", name: "Access" },
          { id: "Customer Created Shipments print", name: "Print" },
          { id: "Customer Created Shipments update", name: "Update" },
        ],
      },
      {
        label: "Shipment Status",
        path: "/shipment-status",
        icon: LineChart,
        permissionKey: "Shipment Status access",
        permissions: [
          { id: "Shipment Status access", name: "View" },
          { id: "Shipment Status create", name: "Create" },
        ],
      },
      {
        label: "Update Shipment Status",
        path: "/update-shipment-status",
        icon: Home,
        permissionKey: "Operation access",
        permissions: [{ id: "Operation update", name: "Update" }],
      },
      {
        label: "Delivery Exceptions",
        path: "/delivery-exceptions",
        icon: AlertTriangle,
        permissionKey: "Delivery Exception access",
        permissions: [
          { id: "Delivery Exception access", name: "View" },
          { id: "Delivery Exception create", name: "Create" },
          { id: "Delivery Exception update", name: "Edit" },
          { id: "Delivery Exception delete", name: "Delete" },
        ],
      },
      {
        label: "Reprint",
        path: "/reprint",
        icon: Printer,
        permissionKey: "Reprint access",
        permissions: [{ id: "Reprint access", name: "View" }],
      },
      {
        label: "NDR List",
        path: "/ndr",
        icon: AlertCircle,
        permissionKey: "Problems access",
        permissions: [
          { id: "Problems access", name: "View" },
          // { id: "Drivers access", name: "View" },
          // { id: "Company access", name: "View" },
          // { id: "Delivery Exception access", name: "View" },
        ],
      },
    ],
  },
  {
    label: "Driver Management",
    icon: User2,
    permissionKeys: [
      "Drivers access",
      "Driver Status access",
      "Driver Account access",
      "Driver Runsheet access",
      "Quality Check access",
      "Address Updates access",
      "OFD List access",
      "Fine access",
    ],
    permissions: [
      { id: "Drivers access", name: "View" },
      { id: "Driver Status access", name: "View" },
      { id: "Driver Account access", name: "View" },
      { id: "Driver Runsheet access", name: "View" },
      { id: "Quality Check access", name: "View" },
      { id: "Address Updates access", name: "View" },
      { id: "OFD List access", name: "View" },
      { id: "Fine access", name: "View" },
    ],
    items: [
      {
        label: "Drivers",
        path: "/drivers",
        plusLink: "/users/create-driver",
        icon: Users,
        isQuickLink: false,
        permissionKey: "Drivers access",
        permissions: [
          { id: "Drivers access", name: "View" },
          { id: "Drivers create", name: "Create" },
          { id: "Drivers update", name: "Edit" },
          { id: "Drivers delete", name: "Delete" },
          { id: "Drivers export", name: "Export" },
        ],
      },
      {
        label: "Driver Status",
        path: "/driver-status",
        icon: Users,
        permissionKey: "Driver Status access",
        permissions: [
          { id: "Driver Status access", name: "View" },
          { id: "Driver Status create", name: "Create" },
          { id: "Driver Status update", name: "Edit" },
          { id: "Driver Status delete", name: "Delete" },
          { id: "Driver Status export", name: "Export" },
        ],
      },
      {
        label: "Drivers Accounts",
        path: "/drivers-accounts",
        icon: Wallet,
        permissionKey: "Driver Account access",
        permissions: [
          { id: "Driver Account access", name: "View" },
          { id: "Driver Account create", name: "Create" },
          { id: "Driver Account update", name: "Edit" },
          { id: "Driver Account delete", name: "Delete" },
          { id: "Driver Account export", name: "Export" },
        ],
      },
      {
        label: "Driver Runsheet",
        path: "/driver-runsheet",
        icon: FileText,
        permissionKey: "Driver Runsheet access",
        permissions: [
          { id: "Driver Runsheet access", name: "View" },
          { id: "Driver Runsheet create", name: "Create" },
          { id: "Driver Runsheet update", name: "Edit" },
          { id: "Driver Runsheet delete", name: "Delete" },
        ],
      },
      {
        label: "Quality Check",
        path: "/quality-check",
        icon: CheckCircle,
        permissionKey: "Quality Check access",
        permissions: [
          { id: "Quality Check access", name: "View" },
          { id: "Quality Check create", name: "Create" },
          { id: "Quality Check update", name: "Edit" },
          { id: "Quality Check delete", name: "Delete" },
          { id: "Quality Check send warning", name: "Send Warning" },
        ],
      },
      {
        label: "Address Updates",
        path: "/address-updates",
        icon: Map,
        permissionKey: "Address Updates access",
        permissions: [
          { id: "Address Updates access", name: "View" },
          { id: "Address Updates create", name: "Create" },
          { id: "Address Updates update", name: "Edit" },
          { id: "Address Updates delete", name: "Delete" },
        ],
      },
      {
        label: "OFD List",
        path: "/ofd-list",
        icon: Clipboard,
        permissionKey: "OFD List access",
        permissions: [
          { id: "OFD List access", name: "View" },
          { id: "OFD List create", name: "Create" },
          { id: "OFD List update", name: "Edit" },
          { id: "OFD List delete", name: "Delete" },
        ],
      },
      {
        label: "Fines",
        path: "/fines",
        icon: DollarSign,
        permissionKey: "Fine access",
        permissions: [
          { id: "Fine access", name: "View" },
          { id: "Fine create", name: "Create" },
          { id: "Fine update", name: "Edit" },
          { id: "Fine delete", name: "Delete" },
        ],
      },
      {
        label: "Driver Warnings",
        path: "/driver-warnings",
        icon: AlertCircle,
        permissionKey: "Fine access",
        permissions: [
          { id: "Fine access", name: "View" },
          { id: "Fine create", name: "Create" },
          { id: "Fine update", name: "Edit" },
          { id: "Fine delete", name: "Delete" },
        ],
      },
    ],
  },
  {
    label: "Logistics Tasks",
    icon: Truck,
    permissionKeys: [
      "Pickup Task access",
      "Assign Pickup Task access",
      "Transfer Task access",
      "Truck access",
      "Truck Driver access",
    ],
    permissions: [
      { id: "Pickup Task access", name: "View" },
      { id: "Assign Pickup Task access", name: "View" },
      { id: "Transfer Task access", name: "View" },
      { id: "Truck access", name: "View" },
      { id: "Truck Driver access", name: "View" },
    ],
    items: [
      {
        label: "Pickup Task",
        path: "/pickup-tasks",
        icon: Package,
        permissionKey: "Pickup Task access",
        permissions: [
          { id: "Pickup Task access", name: "View" },
          { id: "Pickup Task create", name: "Create" },
          { id: "Pickup Task update", name: "Edit" },
          { id: "Pickup Task delete", name: "Delete" },
        ],
      },
      {
        label: "Assign Pickup Task",
        path: "/assign-pickup-tasks",
        icon: Truck,
        permissionKey: "Assign Pickup Task access",
        permissions: [
          { id: "Assign Pickup Task access", name: "View" },
          { id: "Assign Pickup Task create", name: "Create" },
        ],
      },
      {
        label: "Shipment Transfer Tasks",
        path: "/shipments/transfer-tasks",
        icon: ShoppingCart,
        permissionKey: "Transfer Task access",
        permissions: [
          { id: "Transfer Task access", name: "View" },
          { id: "Transfer Task create", name: "Create" },
          { id: "Transfer Task update", name: "Edit" },
          { id: "Transfer Task delete", name: "Delete" },
        ],
      },
      {
        label: "Transfers Areas",
        path: "/transfer-areas",
        icon: Pin,
        permissionKey: "Transfer Task access",
        permissions: [
          { id: "Transfer Task access", name: "View" },
          { id: "Transfer Task create", name: "Create" },
          { id: "Transfer Task update", name: "Edit" },
          { id: "Transfer Task delete", name: "Delete" },
        ],
      },
      {
        label: "Truck",
        path: "/trucks",
        icon: Truck,
        permissionKey: "Truck access",
        permissions: [
          { id: "Truck access", name: "View" },
          { id: "Truck create", name: "Create" },
          { id: "Truck update", name: "Edit" },
          { id: "Truck delete", name: "Delete" },
          { id: "Truck print", name: "Print" },
          { id: "Truck export", name: "Export" },
        ],
      },
      {
        label: "Truck Driver",
        path: "/truck-drivers",
        icon: User,
        permissionKey: "Truck Driver access",
        permissions: [
          { id: "Truck Driver access", name: "View" },
          { id: "Truck Driver create", name: "Create" },
          { id: "Truck Driver update", name: "Edit" },
          { id: "Truck Driver delete", name: "Delete" },
          { id: "Truck Driver export", name: "Export" },
        ],
      },
    ],
  },
  {
    label: "Warehouse Operations",
    icon: Store,
    permissionKeys: [
      "Shelf access",
      "Shelf Category access",
      "StockOutTask access",
    ],
    permissions: [
      { id: "Shelf access", name: "View" },
      { id: "Shelf Category access", name: "View" },
      { id: "StockOutTask access", name: "View" },
    ],
    items: [
      {
        label: "Shelf",
        path: "/shelves",
        icon: Library,
        permissionKey: "Shelf access",
        permissions: [
          { id: "Shelf access", name: "View" },
          { id: "Shelf create", name: "Create" },
          { id: "Shelf update", name: "Edit" },
          { id: "Shelf delete", name: "Delete" },
        ],
      },
      {
        label: "Shelf Shipments",
        path: "/shelf-shipments",
        icon: ShoppingCart,
        permissionKey: "Shelf access",
        permissions: [
          { id: "Shelf access", name: "View" },
          { id: "Shelf create", name: "Create" },
          { id: "Shelf update", name: "Edit" },
          { id: "Shelf delete", name: "Delete" },
        ],
      },
      {
        label: "Shelf Categories",
        path: "/shelf-categories",
        icon: Tags,
        permissionKey: "Shelf Category access",
        permissions: [
          { id: "Shelf Category access", name: "View" },
          { id: "Shelf Category create", name: "Create" },
          { id: "Shelf Category update", name: "Edit" },
          { id: "Shelf Category delete", name: "Delete" },
        ],
      },
      {
        label: "Stock Out Tasks",
        path: "/stock-out",
        icon: BaggageClaim,
        permissionKey: "StockOutTask access",
        permissions: [
          { id: "StockOutTask access", name: "View" },
          { id: "StockOutTask create", name: "Create" },
          { id: "StockOutTask update", name: "Edit" },
          { id: "StockOutTask delete", name: "Delete" },
        ],
      },
    ],
  },
  {
    label: "Stakeholders Management",
    icon: Layers,
    permissionKeys: [
      "Merchant access",
      "Merchant Waybill access",
      "Merchant Account access",
      "Company access",
      "Financial Request access",
      "Shipper access",
      "Consignee access",
    ],
    permissions: [
      { id: "Merchant access", name: "View" },
      { id: "Merchant Waybill access", name: "View" },
      { id: "Merchant Account access", name: "View" },
      { id: "Company access", name: "View" },
      { id: "Financial Request access", name: "View" },
      { id: "Shipper access", name: "View" },
      { id: "Consignee access", name: "View" },
    ],
    items: [
      {
        label: "Merchants",
        path: "/merchants",
        icon: Users,
        permissionKey: "Merchant access",
        permissions: [
          { id: "Merchant access", name: "View" },
          { id: "Merchant create", name: "Create" },
          { id: "Merchant update", name: "Edit" },
          { id: "Merchant delete", name: "Delete" },
        ],
      },
      {
        label: "Merchant Waybills",
        path: "/merchant/waybills",
        dynamicPath: (userId) => `/merchant/view-merchant-waybill/${userId}`,
        icon: Tag,
        permissionKey: "Merchant Waybill access",
        permissions: [
          { id: "Merchant Waybill access", name: "View" },
          { id: "Merchant Waybill create", name: "Create" },
          { id: "Merchant Waybill update", name: "Edit" },
          { id: "Merchant Waybill delete", name: "Delete" },
        ],
      },
      {
        label: "Driver Waybills",
        path: "/driver/waybills",
        dynamicPath: (userId) => `/driver/view-merchant-waybill/${userId}`,
        icon: Tag,
        permissionKey: "driver Waybill access",
        permissions: [
          { id: "driver Waybill access", name: "View" },
          { id: "driver Waybill create", name: "Create" },
          { id: "driver Waybill update", name: "Edit" },
          { id: "driver Waybill delete", name: "Delete" },
        ],
      },
      {
        label: "Merchant Accounts",
        path: "/merchants-accounts",
        icon: Wallet,
        permissionKey: "Merchant Account access",
        permissions: [{ id: "Merchant Account access", name: "View" }],
      },
      {
        label: "Companies",
        path: "/companies",
        icon: Home,
        permissionKey: "Company access",
        permissions: [
          { id: "Company access", name: "View" },
          { id: "Company create", name: "Create" },
          { id: "Company update", name: "Edit" },
          { id: "Company delete", name: "Delete" },
        ],
      },
      {
        label: "Financial Requests",
        path: "/requestsFinancial",
        icon: Home,
        permissionKey: "Financial Request access",
        permissions: [
          { id: "Financial Request access", name: "View" },
          { id: "Financial Request create", name: "Create" },
          { id: "Financial Request update", name: "Edit" },
          { id: "Financial Request delete", name: "Delete" },
        ],
      },
      {
        label: "Shippers",
        path: "/shippers",
        icon: Truck,
        permissionKey: "Shipper access",
        permissions: [
          { id: "Shipper access", name: "View" },
          { id: "Shipper create", name: "Create" },
          { id: "Shipper update", name: "Edit" },
          { id: "Shipper delete", name: "Delete" },
        ],
      },
      {
        label: "Consignee",
        path: "/consignees",
        icon: User,
        permissionKey: "Consignee access",
        permissions: [
          { id: "Consignee access", name: "View" },
          { id: "Consignee create", name: "Create" },
          { id: "Consignee update", name: "Edit" },
          { id: "Consignee delete", name: "Delete" },
        ],
      },
    ],
  },
  {
    label: "Financials",
    icon: DollarSign,
    permissionKeys: [
      "Salary Bill Management access",
      "Manifest Management access",
      "Workspace access",
      "COD collections access",
      "Expense access",
      "Transfer access",
    ],
    permissions: [
      { id: "Salary Bill Management access", name: "View" },
      { id: "Manifest Management access", name: "View" },
      { id: "Workspace access", name: "View" },
      { id: "COD collections access", name: "View" },
      { id: "Expense access", name: "View" },
      { id: "Transfer access", name: "View" },
    ],
    items: [
      {
        label: "Salary Bill Management",
        path: "/salary-bill-management",
        icon: FileText,
        permissionKey: "Salary Bill Management access",
        permissions: [
          { id: "Salary Bill Management access", name: "View" },
          { id: "Salary Bill Management create", name: "Create" },
          { id: "Salary Bill Management update", name: "Edit" },
          { id: "Salary Bill Management delete", name: "Delete" },
        ],
      },
      {
        label: "Manifest Management",
        path: "/manifest-management",
        icon: Package,
        permissionKey: "Manifest Management access",
        permissions: [{ id: "Manifest Management access", name: "View" }],
      },
      {
        label: "Workspace Accounts",
        path: "/workspace-accounts",
        icon: Wallet,
        permissionKey: "Workspace access",
        permissions: [{ id: "Workspace access", name: "View" }],
      },
      {
        label: "COD Collection",
        isQuickLink: false,
        path: "/cod",
        icon: CreditCard,
        permissionKey: "COD collections access",
        permissions: [
          { id: "COD collections access", name: "View" },
          { id: "COD collections create", name: "Create" },
          { id: "COD collections update", name: "Edit" },
          { id: "COD collections delete", name: "Delete" },
        ],
      },
      {
        label: "Expenses",
        path: "/expenses",
        icon: TrendingDown,
        permissionKey: "Expense access",
        permissions: [{ id: "Expense access", name: "View" }],
      },
      {
        label: "Fee Management",
        path: "/fees",
        icon: CreditCard,
        permissionKey: "Expense access",
        permissions: [{ id: "Expense access", name: "View" }],
      },
      {
        label: "Transfers",
        path: "/transfers",
        icon: Repeat,
        permissionKey: "Transfer access",
        permissions: [{ id: "Transfer access", name: "View" }],
      },
    ],
  },
  {
    label: "Partners",
    icon: Users,
    permissionKeys: [
      "Partner Dashboard access",
    ],
    permissions: [
      { id: "Partner Dashboard access", name: "View" },
    ],
    items: [
      {
        label: "Accounts",
        path: "/partner-management/accounts",
        icon: Users,
        permissionKey: "Partner Dashboard access",
        permissions: [{ id: "Partner Dashboard access", name: "View" }],
      },
      {
        label: "Webhooks",
        path: "/partner-management/webhooks",
        icon: MessageCircle,
        permissionKey: "Partner Dashboard access",
        permissions: [{ id: "Partner Dashboard access", name: "View" }],
      },
    ],
  },
  {
    label: "System Logs",
    icon: FileText,
    permissionKeys: [
      "Activity Log access",
      "User Action access",
      "Session access",
      "Login History access",
    ],
    permissions: [
      { id: "Activity Log access", name: "View" },
      { id: "User Action access", name: "View" },
      { id: "Session access", name: "View" },
      { id: "Login History access", name: "View" },
    ],
    items: [
      {
        label: "Audit Logs",
        icon: FileLock,
        permissionKeys: ["Activity Log access", "User Action access"],
        permissions: [
          { id: "Activity Log access", name: "View" },
          { id: "User Action access", name: "View" },
        ],
        items: [
          {
            label: "Activity Logs",
            icon: Activity,
            permissionKey: "Activity Log access",
            permissions: [
              { id: "Activity Log access", name: "View" },
              { id: "Activity Log create", name: "Create" },
              { id: "Activity Log update", name: "Edit" },
              { id: "Activity Log delete", name: "Delete" },
            ],
            path: "/activity-logs",
          },
          {
            label: "User Actions",
            icon: User,
            permissionKey: "User Action access",
            permissions: [
              { id: "User Action access", name: "View" },
              { id: "User Action create", name: "Create" },
              { id: "User Action update", name: "Edit" },
              { id: "User Action delete", name: "Delete" },
            ],
            path: "/user-actions",
          },
        ],
      },
      {
        label: "Access Logs",
        icon: Lock,
        permissionKeys: ["Session access", "Login History access"],
        permissions: [
          { id: "Session access", name: "View" },
          { id: "Login History access", name: "View" },
        ],
        items: [
          {
            label: "Sessions Management",
            icon: Server,
            permissionKey: "Session access",
            permissions: [
              { id: "Session access", name: "View" },
              { id: "Session create", name: "Create" },
              { id: "Session update", name: "Edit" },
              { id: "Session delete", name: "Delete" },
            ],
            path: "/sessions-management",
          },
          {
            label: "Login History",
            icon: LogIn,
            permissionKey: "Login History access",
            permissions: [
              { id: "Login History access", name: "View" },
              { id: "Login History create", name: "Create" },
              { id: "Login History update", name: "Edit" },
              { id: "Login History delete", name: "Delete" },
            ],
            path: "/login-history",
          },
        ],
      },
    ],
  },
  {
    label: "Customer Support",
    icon: Headphones,
    permissionKeys: [
      "CRM Task access",
      "Ticket access",
      "Live Chat access",
      "Merchant Ticket Chat access",
      "Whatsapp Template access",
    ],
    permissions: [
      { id: "CRM Task access", name: "View" },
      { id: "Ticket access", name: "View" },
      { id: "Live Chat access", name: "View" },
      { id: "Merchant Ticket Chat access", name: "View" },
      { id: "Whatsapp Template access", name: "View" },
    ],
    items: [
      {
        label: "Crm Tasks",
        path: "/crm-tasks",
        icon: CheckSquare,
        permissionKey: "CRM Task access",
        permissions: [
          { id: "CRM Task access", name: "View" },
          { id: "CRM Task create", name: "Create" },
          { id: "CRM Task update", name: "Edit" },
          { id: "CRM Task delete", name: "Delete" },
        ],
      },
      {
        label: "Tickets",
        path: "/tickets",
        icon: Ticket,
        permissionKey: "Ticket access",
        permissions: [
          { id: "Ticket access", name: "View" },
          { id: "Ticket create", name: "Create" },
          { id: "Ticket update", name: "Edit" },
          { id: "Ticket delete", name: "Delete" },
        ],
      },
      {
        label: "Live Chat",
        path: "/live-chat",
        icon: MessageCircle,
        permissionKey: "Live Chat access",
        permissions: [
          { id: "Live Chat access", name: "View" },
          { id: "Live Chat create", name: "Create" },
          { id: "Live Chat update", name: "Edit" },
          { id: "Live Chat delete", name: "Delete" },
        ],
      },
      {
        label: "Merchants Chat",
        path: "/merchant-chat",
        icon: MessageCircle,
        permissionKey: "Merchant Ticket Chat access",
        permissions: [
          { id: "Merchant Ticket Chat access", name: "View" },
          { id: "Merchant Ticket Chat create", name: "Create" },
          { id: "Merchant Ticket Chat update", name: "Edit" },
          { id: "Merchant Ticket Chat delete", name: "Delete" },
        ],
      },
      {
        label: "Templates",
        path: "/whatsapp/whatsapp-templates",
        icon: PhoneIcon,
        permissionKey: "Whatsapp Template access",
        permissions: [
          { id: "Whatsapp Template access", name: "View" },
          { id: "Whatsapp Template create", name: "Create" },
          { id: "Whatsapp Template update", name: "Edit" },
          { id: "Whatsapp Template delete", name: "Delete" },
        ],
      },
    ],
  },
  {
    label: "Outsourced Drivers",
    icon: ShieldCheck,
    permissionKeys: [
      "Guest Driver access",
      "Guest Driver Shipment access",
      "Guest Customer Shipment access",
    ],
    permissions: [
      { id: "Guest Driver access", name: "View" },
      { id: "Guest Driver Shipment access", name: "View" },
      { id: "Guest Customer Shipment access", name: "View" },
    ],
    items: [
      {
        label: "Guest Drivers",
        path: "/guest-drivers",
        icon: FileText,
        permissionKey: "Guest Driver access",
        permissions: [
          { id: "Guest Driver access", name: "View" },
          { id: "Guest Driver create", name: "Create" },
          { id: "Guest Driver update", name: "Edit" },
          { id: "Guest Driver delete", name: "Delete" },
        ],
      },
      {
        label: "Guest Driver Shipments",
        path: "/guest-driver-shipments",
        icon: AlertTriangle,
        permissionKey: "Guest Driver Shipment access",
        permissions: [
          { id: "Guest Driver Shipment access", name: "View" },
          { id: "Guest Driver Shipment create", name: "Create" },
          { id: "Guest Driver Shipment update", name: "Edit" },
          { id: "Guest Driver Shipment delete", name: "Delete" },
        ],
      },
      {
        label: "Guest Customer Leads",
        path: "/guest-customers",
        icon: ClipboardCheck,
        permissionKey: "Guest Customer Shipment access",
        permissions: [
          { id: "Guest Customer Shipment access", name: "View" },
          { id: "Guest Customer Shipment create", name: "Create" },
          { id: "Guest Customer Shipment update", name: "Edit" },
          { id: "Guest Customer Shipment delete", name: "Delete" },
        ],
      },
    ],
  },
];
